/*
 * Copyright 2020 Patrik Karlström.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.nbpackager_core;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import java.util.prefs.Preferences;
import static se.trixon.nbpackager_core.Options.*;

/**
 *
 * @author Patrik Karlström
 */
public class ProfilePanel extends javax.swing.JPanel {

    private final Options mOptions = Options.getInstance();

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
    }

    void loadProfile(String profile) {

    }

    void removeProfile(String profile) {
        Preferences p = mOptions.getPreferences().node(KEY_PROFILES).node(profile);
        try {
            p.removeNode();
        } catch (BackingStoreException ex) {
            Logger.getLogger(ProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void saveProfile(String profile) {
        Preferences p = mOptions.getPreferences().node(KEY_PROFILES).node(profile);

//        p.put(KEY_PROFILE_OUTPUT, outputFileChooserPanel.getPath());
//        List<String> vvv = jmodsList.getSelectedValuesList();
//        p.put(KEY_PROFILE_MODULES, String.join(",", vvv));
//        p.put(KEY_PROFILE_CUSTOM_MODULE_PATH, customModulePathTextArea.getText());
//        p.put(KEY_PROFILE_CUSTOM_MODULES, customModulesTextArea.getText());
//        p.putBoolean(KEY_PROFILE_BIND_SERVICES, bindServicesCheckBox.isSelected());
//        p.putBoolean(KEY_PROFILE_IGNORE_SIGNING, signingCheckBox.isSelected());
//        p.putBoolean(KEY_PROFILE_NO_HEADER, headersCheckBox.isSelected());
//        p.putBoolean(KEY_PROFILE_NO_MAN, manCheckBox.isSelected());
//        p.putBoolean(KEY_PROFILE_STRIP_DEBUG, stripCheckBox.isSelected());
//        p.putInt(KEY_PROFILE_COMPRESS, compressComboBox.getSelectedIndex());
//        p.putInt(KEY_PROFILE_ENDIAN, endianComboBox.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserPanel1 = new se.trixon.almond.util.swing.dialogs.FileChooserPanel();

        fileChooserPanel1.setCheckBoxMode(false);
        fileChooserPanel1.setMode(1);
        fileChooserPanel1.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooserPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private se.trixon.almond.util.swing.dialogs.FileChooserPanel fileChooserPanel1;
    // End of variables declaration//GEN-END:variables
}
