/*
 * Copyright 2020 Patrik Karlström.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.nbpackager;

import java.awt.BorderLayout;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import se.trixon.nbpackager_core.OptionsPanel;

final class PackagerOptionsPanel extends javax.swing.JPanel {

    private final PackagerOptionsPanelController mController;
    private final OptionsPanel mOptionsPanel;

    PackagerOptionsPanel(PackagerOptionsPanelController controller) {
        mController = controller;
        initComponents();
        add(mOptionsPanel = new OptionsPanel(), BorderLayout.CENTER);
        mOptionsPanel.setDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                mController.changed();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                mController.changed();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                mController.changed();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        mOptionsPanel.load();
    }

    void store() {
        mOptionsPanel.save();
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
